[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --log-level info"
