[theme]
primaryColor = "#0072CE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false
